### ISSUE TITLE
Image Horoscope

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#69]
Bonjour, 

L'image d'un contenu horoscope n'est pas la même dans la page de liste horoscope et dans sa page détail.
Soit il faut supprimer l'illustration pour ces contenus horoscopes soit il faut garder la cohérence entre les deux images.
Merci
Lidwine
 
![page liste horoscope](https://user-images.githubusercontent.com/45075533/53577935-d8251780-3b76-11e9-90e1-6484766c0201.png)
![page detail horoscope](https://user-images.githubusercontent.com/45075533/53577936-d8251780-3b76-11e9-940c-36ac0ffb1fc3.png)

**Comment by nicolastrenti** [comment]
Lidwine,

Il s'agit en fait d'une question liée à la contribution des articles dans WordPress.
L'image affichée dans les pages de liste est celle déclarée comme mise en avant dans l'article WordPress (en bas à droite de l'interface de contribution) : 

![image](https://user-images.githubusercontent.com/1919354/53633036-ab284180-3c16-11e9-9068-2008a88b887f.png)

L'image affichée sur le détail d'article est celle qui figure dans le corps de l'article : 

![image](https://user-images.githubusercontent.com/1919354/53633084-c8f5a680-3c16-11e9-940c-9159525b0908.png)

Libre au contributeur de mettre une même image ou une image différente.
Pour éviter toute confusion, j'ai uniformisé les deux images sur cet article.
