### ISSUE TITLE
URL Agenda

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#70]
Bonjour, 

L'url de la catégorie Agenda est : https://tmv-qual.nrco.fr/agenda et n'intègre pas le terme "catégory" comme les autres rubriques, est-ce normal ? 

Merci
Lidwine

**Comment by nicolastrenti** [comment]
Oui, c'est normal : toutes les autres pages correspondent à des listes d'articles issus de catégories Wordpress, mais la page Agenda est un peu spécifique. En effet, elle comporte la fameuse iframe qui inclut la recherche. Elle n'est donc pas construite sur le même modèle que les autres pages.
