### ISSUE TITLE
Didomi sur version mobile

### ISSUE THREAD

**Issue by liret** [ampize/ampize-nr-tmv#71]
Didomi ne s'affiche pas correctement sur la version mobile.

Il est impossible d'accepter ou refuser Didomi, ni même de le fermer malgré la croix en haut à droite.

![capture didomi sur mobile](https://user-images.githubusercontent.com/41443023/53578062-233f2a80-3b77-11e9-9b91-811af73684e9.png)

**Comment by nicolastrenti** [comment]
Effectivement, je reproduis le problème. Nous allons corriger.

**Comment by nicolastrenti** [comment]
Corrigé par l'ajout d'un overflow:scroll sur la div consent-ui
En attente de livraison, ne pas retester pour l'instant

**Comment by LidwineMALTETE** [comment]
Bonjour, 

retesté de mon côté, cela semble fonctionner. 

A bientôt, 
Lidwine
