### ISSUE TITLE
Action "Nous contacter"

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#72]
Bonjour, 

En HP lorsque l'on clique sur l'enveloppe de contact, le temps de réponse avant que le logiciel de messagerie ne s'ouvre et parfois très long (plusieurs minutes ou affiche même un message d'erreur) sur certains postes. Est-ce un problème côté logiciel de messagerie ? 

Merci
Lidwine

**Comment by nicolastrenti** [comment]
Lidwine,

Il s'agit de balises href="mailto:" tout à fait standards, le site ne peut pas avoir d'influence sur la durée d'ouverture du logiciel de messagerie.
Je viens de refaire un test et chez moi l'ouverture de gmail par exemple est instantanée.
