### ISSUE TITLE
GA sur version mobile TMV

### ISSUE THREAD

**Issue by liret** [ampize/ampize-nr-tmv#73]
Bonjour,

Les audiences mobiles ne remontent pas correctement sur GA.

Pour une page consultée sur le site TMV, GA va comptabiliser 4, 5 ou 7 pages vues selon le type de page.

**Comment by nicolastrenti** [comment]
Lidwine,
Pouvez-vous me donner accès à ce compte Google Analytics pour que je puisse faire des tests et analyser la situation ?
Merci

**Comment by nicolastrenti** [comment]
C'est a priori corrigé dorénavant (penser à visualiser les pages en rajoutant ?no-cache=true dans l'URL pour éviter les effets de cache pour l'instant).

**Comment by dfanchon** [comment]
Bonjour Hélène,
Merci de bien vouloir tester la correction et fermer l'anomalie si elle est corrigée.

**Comment by liret** [comment]
Même retour que sur le ticket #75.

**Comment by nicolastrenti** [comment]
Hélène,
Nous n'avons aucune maîtrise sur le cache. Le faible trafic sur le site de recette explique que le rafraîchissement de cache soit si peu fréquent.
Si la correction fonctionne avec no-cache=true, c'est qu'elle sera bien effective en prod.
