### ISSUE TITLE
Recherche

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#74]
Bonjour, 

2 Problèmes avec la recherche : 

* la fonctionnalité disparait sur les écrans tablettes et smartphones. Il faudrait conserver la loupe dans la version tablette et l'intégrer au burger menu dans la version smartphone.

* Lorsque l'on clique sur la loupe pour effectuer une recherche, une fois le texte de recherche entré, rien n'indique comment lancer la recherche. Tous les internautes n'auront pas l'intuition de cliquer sur "Enter" aussi il serait peut être bon d'ajouter un bouton "ok"  dans la barre de recherche pour lancer l'action. 

Merci
Lidwine

**Comment by nicolastrenti** [comment]
Corrigé, en attente de déploiement

**Comment by nicolastrenti** [comment]
C'est fait, Lidwine : bouton ajouté dans la recherche desktop, et la recherche passe dans le menu latéral pour les petites résolution

**Comment by LidwineMALTETE** [comment]
Bonjour Nicolas, 

Merci pour ce retour. Pour l'entrée dans le burger pour les petites résolutions, cela fonctionne très bien. En revanche, le bouton "ok" disparait lorsque l'on appelle le module de recherche depuis certaines rubriques. J'ai bien vidé mes caches mes l'affichage du bouton est aléatoire. Nous avons fait le test avec un navigateur depuis lequel nous n'avions jamais exploré le site et même constat, on le voit depuis certaines rubriques mais pas depuis d'autres (notamment les rubriques "écrans", "tendance" et "culture" depuis le burger.) 
![image](https://user-images.githubusercontent.com/45075533/55340327-c0f28600-54a4-11e9-986b-b362e6046e0d.png)

A bientôt, 
Lidwine

**Comment by dfanchon** [comment]
Problème non constaté sur:
- https://tmv-qual.nrco.fr/category/ecrans/?no-cache
- https://tmv-qual.nrco.fr/category/tendances/?no-cache
- https://tmv-qual.nrco.fr/category/culture?no-cache=true

pensez bien à rajouter no-cache=true sur chaque page, cette information n'est pas conservée lorsque vous naviguez.

**Comment by LidwineMALTETE** [comment]
OK. On lance comme ça et on verra si le problème se reproduit une fois en prod. Dans tous les cas ce n'est pas un sujet bloquant.
