### ISSUE TITLE
KPIs spécifiques sur TMV

### ISSUE THREAD

**Issue by liret** [ampize/ampize-nr-tmv#75]
Bonjour,

Nous souhaiterions faire développer des KPIs spécifiques non disponibles nativement dans GA.

De quoi avez-vous besoin pour effectuer ce développement ?

Voici la liste ci-dessous :

- Tracker les clics sur le bouton Téléchargement des pdf sur la Home.

Si nous ne disposons pas d'une url différente pour chaque pdf dans la rubrique "L'Hebdo PDF", tracker les clics sur chaque pdf et renvoyer le clic et la date de diffusion du journal.

- Tracker les clics sur les articles de la catégorie "Vous aimerez aussi"

- Tracker les clics sur les articles de la catégorie "Les plus lus"

- Tracker les clics sur les icônes de partage (Facebook et Twitter de manière indépendante) affichées dans un article

**Comment by nicolastrenti** [comment]
Bonjour Hélène,

Les KPIs suivants ont été implémentés : 
- clics sur le bouton Téléchargement des pdfs, avec les propriétés suivantes : 
```
"event_name": "download",
"event_category": "pdf", 
"event_label": "{{titre_du_PDF}}"
```
- clics sur les articles de la catégorie "Vous aimerez aussi", avec les propriétés suivantes : 
```
"event_name": "lien-vous-aimerez-aussi",
"event_category": "article", 
"event_label": "{{titre_article}}"
```
- clics sur les articles de la catégorie "Les plus lus"
```
"event_name": "lien-les-plus-lus",
"event_category": "article", 
"event_label": "{{titre_article}}"
```

Pour les clics sur les icônes de partage, c'est impossible à tracker en AMP.

**Comment by liret** [comment]
Bonjour Nicolas,

J'ai testé vendredi 1er mars ces événements, mais rien ne remonte dans le temps réel et l'historisation GA. Ces KPIs sont-ils implémentés sur un autre environnement de test ?

**Comment by nicolastrenti** [comment]
Bonjour Hélène,

Je viens de me connecter à votre compte GA et je vois bien de mon côté des événements qui remontent.
Ici les liens "Vous aimerez aussi" par exemple (et on a bien la même chose pour les downloads et les liens "les articles les plus lus")  :

![image](https://user-images.githubusercontent.com/1919354/54286997-2689db80-45a5-11e9-9578-3a38ea5a77d5.png)

**Comment by nicolastrenti** [comment]
Et je les vois bien en temps réel également : 
![image](https://user-images.githubusercontent.com/1919354/54287480-03136080-45a6-11e9-9f68-073c7c8bf8e0.png)

**Comment by liret** [comment]
Bonjour,
J'ai refait des tests ce matin et les événements ne remontent pas sur GA.

![20190314_Evénements GA](https://user-images.githubusercontent.com/41443023/54350988-c94a6480-464e-11e9-9b39-e94fa7fedec9.JPG)

**Comment by nicolastrenti** [comment]
Hélène,
Avez-vous bien accepté le consent dans la première pop-in lors de vos tests ? Si vous n'avez pas répondu (fenêtre fermée sans accepter réellement) ou si vous avez refusé explicitement, les actions utilisateur ne sont pas remontée dans GA.

**Comment by liret** [comment]
J'ai refait 3 tests dans des configurations différentes.

=> Un premier en navigation privée sur desktop. Tous les événements et pages vues remontent correctement dans GA.

=> Un deuxième en navigation normale, sur desktop, sur ma session déjà ouverte. Les pages article remontent correctement dans GA mais pas les événements.

=> Un troisième en vidant mes cookies et avec ouverture d'une nouvelle session puis acceptation de Didomi. Les événements remontent dans GA. Les pages vues sur les articles remontent également mais avec un volume erroné. Pour une page vue, GA en comptabilise 6.

**Comment by nicolastrenti** [comment]
Hélène,
Merci pour ces retours.
J'ai effectué des corrections,  que vous pouvez déjà voir sur votre environnement de qualif (mais attention à bien rajouter ?no-cache=true à la fin des URL pour éviter les effets de cache).
D'après mes tests, maintenant tout est bon : chaque page vue est bien comptabilisée 1 seule fois, et les événements remontent en temps réel.

**Comment by dfanchon** [comment]
Bonjour Hélène,
Merci de bien vouloir tester la correction et fermer l'anomalie si elle est corrigée.

**Comment by liret** [comment]
Le volume de pages vues remonte correctement sur GA lorsque j'ajoute ?no-cache=true.

Quand les effets de cache seront résolus afin que je puisse tester à nouveau avant la MEP ?

**Comment by nicolastrenti** [comment]
Hélène,
Nous n'avons aucune maîtrise sur le cache. Le faible trafic sur le site de recette explique que le rafraîchissement de cache soit si peu fréquent.
Si la correction fonctionne avec no-cache=true, c'est qu'elle sera bien effective en prod.
