### ISSUE TITLE
Contenu rubrique horoscope - catégorie "écrans"

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#76]
Bonjour, 

La plupart des contenus horoscopes sont rattachés à la catégorie "écrans" et ne s'affichent pas au format "horscope". 

https://tmv-qual.nrco.fr/tags?tag=horoscope

De tous ces contenus, un seul est associé à la bonne catégorie et remonte avec le bon format dans la bonne catégorie horoscope : https://tmv-qual.nrco.fr/article/horoscope-wtf-du-19-decembre-au-76-janvier-2094/

Par ailleurs, d'autres contenus sont indûment rattachés à la catégorie "écrans"  (https://tmv-qual.nrco.fr/article/wtf-67-un-apero-30-000-e-pour-ronaldo/) alors que cette catégorie ne doit concerner que le cinéma. 
Comment se tag est-il rattaché aux contenus ? 

Merci 
Lidwine

**Comment by nicolastrenti** [comment]
Lidwine,

Le rattachement à la catégorie Ecran correspond aux consignes de migration des rubriques données par Cécile : 

![image](https://user-images.githubusercontent.com/1919354/53642787-d4ef6180-3c32-11e9-83a9-c3d28117146d.png)

Les horoscopes étaient jusqu'à présent dans la catégorie "Infos du web", ils sont désormais dans "Ecran".
Idem pour les WTF.

Concernant les horoscopes repris, issus de l'ancien site : il n'est pas possible qu'ils s'affichent de manière automatique dans le nouveau format. Il s'agit d'articles comme les autres, que nous affichons tels quels, nous ne pouvons pas les "transformer" à la volée pour changer leur présentation.
Le seul horoscope au nouveau format est celui que j'ai créé pour l'occasion et qui devra servir de modèle pour les futurs articles de type horoscope (qui devront être taggués dans la catégorie Horoscope).

**Comment by LidwineMALTETE** [comment]
Merci Nicolas, 
En fait, comme j'ai repris le tableau de Cécile pour les nouvelles rubriques : 
![image](https://user-images.githubusercontent.com/45075533/53721070-95a75780-3e62-11e9-8736-de51c376ecb2.png)
Je pensais que l'horoscope était déjà une rubrique à part entière alors qu'effectivement, il faisait bien partie de la catégorie "Infos du web" ce qui explique sa reprise dans "Ecrans". 
Je vais demander à Aurélien (le grand manitou du site TMV) de retagguer quelques vieux horoscopes dans la nouvelle catégorie histoire de faire tout de même un peu de fond dans cette rubrique clé de TMV.
