### ISSUE TITLE
Les images n'ont pas été importées dans le nouveau site WP

### ISSUE THREAD

**Issue by liret** [ampize/ampize-nr-tmv#77]
Bonjour,

1/ Lorsque l'on clique sur les photos présentes dans un article, cela ouvre une page d'erreur. Ci-joint les captures d'écrans.

![photo](https://user-images.githubusercontent.com/41443023/53582369-9e0c4380-3b7f-11e9-94a4-ecf9781af9a2.JPG)

![clic photo](https://user-images.githubusercontent.com/41443023/53582387-a8c6d880-3b7f-11e9-9844-51d3784b76f0.JPG)

2/ Certaines photos ne s'affichent pas non plus dans une page article.

![affichage photo](https://user-images.githubusercontent.com/41443023/53582562-0b1fd900-3b80-11e9-94cd-7e04ba49a1fd.JPG)

**Comment by nicolastrenti** [comment]
@dfanchon : à analyser ensemble

**Comment by dfanchon** [comment]
Le premier point semble être un problème d'entête http. Le second est lié au plugin nrm-embed.

**Comment by LidwineMALTETE** [comment]
Bonjour Didier, 

Le problème est partiellement résolu. En fait lorsque l'on clique sur une photo depuis le site tmv-qual.nrco.fr on est renvoyé vers une page www.tmvtours.fr, en erreur. Le renvoi se fait donc faire un site différent du site de consultation de l'image. 
![image](https://user-images.githubusercontent.com/45075533/54614442-b5db3700-4a5c-11e9-9d22-78aece4f894f.png)


Wilfried est à disposition pour échange plus en détails sur le sujet. 

A bientôt, 
Lidwine

**Comment by dfanchon** [comment]
Je pense qu'on vient de lever un sérieux problème. En fait aucun média n'a été repris dans la nouvelle installation wordpress, ils pointent tous sur les images de l'ancien site. Quand celui-ci sera désactivé il n'y aura plus d'images du tout dans les articles ... La procédure de reprise doit être finalisée, à voir si il s'agit d'une option à activer dans le plugin d'import utilisé ou si il faut utiliser un autre plugin. Je rajoute Jean-François dans la boucle et je change le libellé de la fiche.

**Comment by jfozange** [comment]
Suite au dernier import, une partie des photos n'a pas été transférée sur le nouveau serveur. Je verrais ça lundi avec Jerome P.
Si l'url de l'ancien site tmvtours.fr est basculée sur le nouveau wordpress, il n'y aura pas de pb sur l'affichage wordpress des images puisqu'elles seront à nouveau disponibles sur la même URL.
Par contre pour la partie ampize, je ne sais pas comment vous aller gérer ça.
Ce qui est sur, c'est que les images sont dans le corps du texte, et que si l'url doit changer, il faut la modifier dans le corps de l'article, à la volée ou dans la bdd au préalable.
A dispo pour faire un call la semaine prochaine avec Jerome P et vous pour en discuter.

**Comment by dfanchon** [comment]
L'url de l'ancien site sera basculée sur le site AMP, le site wordpress doit juste servir de back-office de saisie. Du coup il va effectivement falloir modifier les urls de toutes les images présentes dans les corps de texte. Ca devrait être faisable en une seule requête SQL, mais il faut au préalable fixer le nom de domaine du site wp, sauf si on peut passer toutes les urls en relatif. Je te laisse en parler avec Jérôme et revenir vers moi.

**Comment by jfozange** [comment]
Lors du premier import d'article il y a quelques mois, j'avais aussi transféré les photos dans wp-content/uploads/sites/tours/... mais il n'y a plus rien.
Vous savez pourquoi ?

**Comment by dfanchon** [comment]
Je ferme cette anomalie à priori corrigée
