### ISSUE TITLE
Listes d'articles

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#79]
Bonjour, 

Dans la version de test, seul un nombre limité d'articles remontent. Il faudrait importer tout l'historique des articles existant sur TMV. 

Merci
Lidwine

**Comment by nicolastrenti** [comment]
@jfozange : Jean-François, c'est possible de ton côté de lancer l'import des articles manquants ?

**Comment by jfozange** [comment]
En principe, il y avait déjà tous les articles jusqu'à Décembre 2018.
Je viens d'importer les articles de décembre à aujourd'hui

**Comment by jfozange** [comment]
Quand on regarde la liste "ARCHIVES", on a les articles depuis Octobre 2011 ... c'est peut-être le front qui limite la liste ?

**Comment by dfanchon** [comment]
Effectivement la maquette que nous avons respectée a été construite autour de blocs de x articles agencés dans la page, mais il n'y a pas de liste paginées, ce qui est surement un manque, ne serait-ce que pour que le site puisse être correctement crawlé par les moteurs de recherche. Je propose dans un premier temps de faire une simple page "archives" paginée listant les articles par ordre anté-chrono.

**Comment by nicolastrenti** [comment]
Page "Archives" implémentée, en attente de livraison

**Comment by LidwineMALTETE** [comment]
Bonjour, 

A priori cela fonctionne plutôt bien mais sur certaines pages, il y a des espaces blancs, est-ce normal ? 
![image](https://user-images.githubusercontent.com/45075533/54545635-56205580-49a2-11e9-87f9-06d0e5a71b08.png)

merci par avance pour ton retour, 

A bientôt, 
Lidwine

**Comment by dfanchon** [comment]
C'est du au fait que certains articles n'ont pas d'image, ce qui décale tout l'affichage. La solution serait peut être d'afficher une image par défaut ?

**Comment by nicolastrenti** [comment]
Corrigé, en attente de déploiement

**Comment by nicolastrenti** [comment]
C'est normalement beaucoup mieux : https://tmv-qual.nrco.fr/archives?category=News&no-cache=true

**Comment by dfanchon** [comment]
A tester et clôturer

**Comment by LidwineMALTETE** [comment]
ça m'a l'air ok ! merci
