### ISSUE TITLE
Problème d'affichage du site sur Internet Explorer

### ISSUE THREAD

**Issue by liret** [ampize/ampize-nr-tmv#80]
Le site TMV ne s'affichage par correctement sur Internet Explorer (version 11).

![TMV sur IE_Capture 1](https://user-images.githubusercontent.com/41443023/54351231-555c8c00-464f-11e9-92c5-0771d7d4173c.JPG)

![TMV sur IE_Capture 2](https://user-images.githubusercontent.com/41443023/54351236-57bee600-464f-11e9-8d5f-795a3a7b8bea.JPG)

![TMV sur IE_Capture 3](https://user-images.githubusercontent.com/41443023/54351238-5a214000-464f-11e9-9028-1574d9c152c1.JPG)

**Comment by dfanchon** [comment]
Effectivement IE n'est pas supporté par AMP : https://www.ampproject.org/support/faqs/supported-browsers
