### ISSUE TITLE
Rubrique Agenda - Ifram NR down

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#82]
Bonjour, 

Depuis les dernières livraisons, l'intégration de l'agenda NR dans la rubrique "Agenda" ne fonctionne plus : 
![image](https://user-images.githubusercontent.com/45075533/54763012-81e74980-4bf5-11e9-8bd5-4fd0e1f11011.png)

Merci

A bientôt, 
Lidwine

**Comment by dfanchon** [comment]
Bonjour. D'après le message d'erreur l'url de l'agenda chez vous n'est plus accessible => à voir avec Jean-François à qui je ré-affecte le bug.

**Comment by jfozange** [comment]
Effectivement, depuis début Février l'agenda loisirs a été migré sur une nouvelle plateforme.
Voici sa nouvelle adresse : https://agenda.lanouvellerepublique.fr/
Le fonctionnement est le même.

**Comment by nicolastrenti** [comment]
Corrigé, en attente de déploiement

**Comment by nicolastrenti** [comment]
C'est corrigé : https://tmv-qual.nrco.fr/agenda?no-cache=true

**Comment by LidwineMALTETE** [comment]
Bonjour Nicolas, 

A priori tout fonctionne bien ! Merci
