### ISSUE TITLE
Implémentation de Didomi

### ISSUE THREAD

**Issue by liret** [ampize/ampize-nr-tmv#87]
Bonjour,

Afin de compléter l'implémentation de Didomi, vous trouverez ci-dessous les éléments nécessaires pour son implémentation.

**1 / Clé API**

Nous disposons d'une clé **API de test** avec l'interface Didomi :
0ed0a260-cf89-4d73-9613-4aa5a107d6ea

Une fois que tout sera validé, vous pourrez utiliser celle de **production** :
08793271-2f36-46e1-9fee-fc591a2dbcd2

**2 / Je vous joins également les liens utiles pour la partie technique :**
- **Documentation détaillée** : https://developers.didomi.io/cmp/web-sdk/getting-started
- **Google Tag Manager** : https://developers.didomi.io/cmp/web-sdk/tags-management/google-tag-manager
- **Customisation de la bannière** :  https://developers.didomi.io/ puis Web SDK => Consent Notice => Customize.

Par rapport à la bannière posée sur le site de test, nous souhaiterions faire évoluer la seconde fenêtre. Lorsque nous cliquons sur "En savoir plus", nous souhaiterions afficher les items de consentement et les partenaires afin de permettre la personnalisation de consentement auprès de l'internaute.

Voici ci-dessous l'exemple sur la NR :
![image](https://user-images.githubusercontent.com/41443023/55339378-d666b080-54a2-11e9-9f99-c2e35df2c140.png)

**3 / Liste des Tags**

Voici la liste des tags spécifiques pour la **Publicité** pour lesquels nous devons récolter le consentement : 
- Partage du consentement à DFP : https://developers.didomi.io/cmp/web-sdk/consent-notice/vendors-and-purposes/google-dfp-adsense-adx
- Liste Vendors IAB (pub) qui peut être amenée à évoluer : "vendors":{"iab":[487,32,285,184,52,128,114,464,343,284,89,264,95,84,71,21,39,236,210,309,132,178,165,79,253,202,98,76,25,45,278,77,68,93,501,225],"didomi":["google"]}

Voici les listes des **autres Tags** qui nécessiteront une intégration manuelle. Pour toute question technique, vous pouvez contacter les personnes suivantes chez Didomi : jawad.stouli@didomi.io et maxime.plancke@didomi.io.
- Onfocus (à déclarer comme des customs vendors)
- Krux (à déclarer comme des customs vendors)
- Header bidding / IAS (Vendors IAB 278)

Est-ce que vous disposez de la liste actuelle des tags / cookies posés sur le site TMV ?

Merci pour votre retour.
Hélène

**Comment by dfanchon** [comment]
Bonjour,

Je ne comprends pas ce ticket. Pour rappel le site TMV est un site AMP, et aux dernières nouvelles Didomi n'était pas implémentable sous AMP. Je ne pense pas que ce sujet ait évolué depuis les dernières discussions avec la NR et Didomi ?

**Comment by liret** [comment]
Bonjour,

Dans ce cas, pouvons-nous implémenter l'AMP consent ?

Est-ce que la fenêtre de consentement présente sur le site de test vient de ce module ?

**Comment by nicolastrenti** [comment]
Bonjour Hélène,

L'AMP consent est justement la solution implémentée pour la bannière de consentement en recette.

Cordialement,
Nicolas

**Comment by liret** [comment]
Bonjour Nicolas,

Où voit-on les informations de consentement, notamment le taux de consentement ?
Y-a-t-il une interface utilisateur ?

Peut-on afficher des catégories de consentement pour que l'utilisateur puisse les personnaliser (ex : Fonctionnement, Web Analytics, Social, Publicité, ...) ?

Même question pour les partenaires ?

Bien cordialement,
Hélène

**Comment by nicolastrenti** [comment]
Hélène,

Non, le composant amp-consent ne permet pas en l'état de personnaliser les catégories. Les seules options possibles sont une acceptation globale, un refus global ou une fermeture de la fenêtre sans choix de l'utilisateur.
Il n'existe pas d'interface permettant de consulter les informations de consentement. 

Bonne journée,
Nicolas
