### ISSUE TITLE
Taille des ads mobile Ban_Haut, Ban_Milieu et Ban_Milieu2

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-nr-tmv#88]
Concernant la publicité, nous avons une modification sur la taille déclarée dans les positions mobile Ban_Haut, Ban_Milieu et Ban_Milieu2.

Peux-tu supprimer la taille 320x50 et remplacer par une multi-size pour déclarer les tailles 320x150 et 320x100 ?

Exemple : 
```
<amp-ad width=320 height=150
    type="doubleclick"
    data-slot="/32200672/xxx"
    data-multi-size="320x150,320x100">
</amp-ad>
```

**Comment by nicolastrenti** [comment]
Correction livrée, en attente de redéploiement sur environnement de qual NR

**Comment by nicolastrenti** [comment]
Correction déployée sur l'environnement de qualification NR : https://tmv-qual.nrco.fr/?no-cache=true

@ansoweb37 : Anne-Sophie, peux-tu me confirmer que ça te convient ? Merci.

**Comment by ansoweb37** [comment]
@nicolastrenti c'est ok ! merci

**Comment by nicolastrenti** [comment]
Merci Anne-Sophie, je ferme le ticket du coup.
