### ISSUE TITLE
Pb de qualité photos

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#89]
Certaines photos sont de mauvaise qualité en front dans les pages listes  alors qu'elles sont importées en bonne qualité dans le back et aussi de bonne qualité dans la page détail. 
Exemple avec la rubrique Pause : 
![image](https://user-images.githubusercontent.com/45075533/56590479-79fd3980-65e7-11e9-8fbf-876fa051b8c5.png)

**Comment by nicolastrenti** [comment]
A priori résolu désormais (taille des vignettes augmentée dans le BO WordPress pour éviter un redimensionnement disgracieux.
