### ISSUE TITLE
Problème de non affichage des vignettes photos 

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#90]
Problème de non affichage de photos dans la rubrique "Vous aimerez aussi" en bas de page détail.
![image](https://user-images.githubusercontent.com/45075533/56590607-a9ac4180-65e7-11e9-831c-abc01a4950bc.png)

mais j'avoue que je ne me souviens plus si c'était prévu....

**Comment by nicolastrenti** [comment]
Oui, il y avait effectivement des vignettes à la base, c'est un problème de paramétrage qui sera corrigé par le prochain déploiement.

**Comment by nicolastrenti** [comment]
Livré en prod : https://www.tmvtours.fr/article/chroniques-culture-67-2/

**Comment by LidwineMALTETE** [comment]
ok ! merci
