### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#93]
La Favicon fournie par Matthieu Pays n'apparaît pas sur le nouveau site. Le format ne convient-il pas ? Si c'est le cas, il faut en redemander un nouveau à Matthieu.

**Comment by nicolastrenti** [comment]
Ce point sera corrigé avec le nouveau déploiement.

**Comment by nicolastrenti** [comment]
Livré en prod.

**Comment by LidwineMALTETE** [comment]
C'est tout bon !
