### ISSUE TITLE
Temps de chargement des pages excessif

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#94]
Le temps de chargement des pages listes est très long (j'ai compté plus de 5 secondes sur certaines rubriques) ce qui peut laisser penser que la page ne va pas s'afficher.

**Comment by nicolastrenti** [comment]
J'ai l'impression que les temps de chargement se sont bien améliorés (c'était le temps de la mise en cache des pages AMP par Google).
Tu confirmes Lidwine ?

**Comment by LidwineMALTETE** [comment]
Bonjour Nicolas, 

Il y a une amélioration sur certaines rubriques mais la HP reste très longue à charger. J'ai compté 5 seconde en ouverture de site et 7 secondes en retour sur la HP en cliquant sur le logo depuis une rubrique du site.

**Comment by nicolastrenti** [comment]
Oui, la home ne peut pas encore être mise en cache car il reste des erreurs AMP (elle ne passe pas la validation actuellement) à cause des publi-infos introuvables.
Le prochain déploiement corrigera ce point.

**Comment by nicolastrenti** [comment]
La Home passe désormais la validation, le temps de réponse me semble maintenant tout à fait correct.

**Comment by LidwineMALTETE** [comment]
En effet, c'est tout à fait correct
