### ISSUE TITLE
Blancs sur la home page en version mobile

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#96]
Sur la HP en version mobile il existe des espaces blancs entre les premiers contenu et le PDF : 
![image](https://user-images.githubusercontent.com/45075533/56595779-8e453480-65ef-11e9-9586-0e42e90d4164.png)
Ainsi qu'avant le fil de Tweets  : 
![image](https://user-images.githubusercontent.com/45075533/56595849-acab3000-65ef-11e9-9610-ebcb0359efc6.png)

**Comment by nicolastrenti** [comment]
Les blancs correspondaient aux blocs Publi-infos, pour lesquels il n'existe aucun article actuellement.
J'ai modifié la configuration de façon à ne pas afficher ces blocs pour l'instant (en attente d'un redéploiement).
Je transmettrai à Anne-Sophie une courte documentation pour lui expliquer comment switcher d'un mode à l'autre lorsqu'il y aura des Publi-infos à afficher. Il s'agira d'une modification simple à réaliser dans le BO AMPize.

**Comment by nicolastrenti** [comment]
Livré en prod.

**Comment by LidwineMALTETE** [comment]
ok pour moi
