### ISSUE TITLE
Problème recherche Google

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#97]
Quand on recherche un article TMV via Google, on ouvre une page d'erreur en cliquant sur le résultat Google; 
Ex : recherche dans Google Nota Bene TMV - 
![image](https://user-images.githubusercontent.com/45075533/56662697-de320300-66a4-11e9-88b3-02fa66505c4a.png)

Alors qu'il existe un article sur le sujet publié sur le nouveau site : 

https://www.tmvtours.fr/article/chroniques-culture-67-2/

**Comment by LidwineMALTETE** [comment]
Cela pose deux questions : 

1) la redirection des URLS anciennes
2) l'indexation du nouveau site par Google

**Comment by nicolastrenti** [comment]
Concernant les redirections, j'ai fourni à la DSI les correspondances entre les anciennes et les nouvelles URLs. Elles devraient donc être implémentées rapidement.

Concernant l'indexation du site, elle sera effectivement dès la prochaine publication du site (en attente de déploiement)

**Comment by nicolastrenti** [comment]
Les anciennes URL indexées par Google refonctionnent.
Exemple : https://www.tmvtours.fr/2019/04/22/dans-2-mois-tmv-debarque-au-hellfest-2.html

**Comment by LidwineMALTETE** [comment]
C'est ok !
