### ISSUE TITLE
Création d'un billet

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#98]
Aurélien aurait besoin de connaître la manip pour créer un Billet depuis le BO Wordpress

**Comment by nicolastrenti** [comment]
Livré, en attente de déploiement.
Le billet sera un article WordPress à part entière, à publier dans une catégorie "billet".
J'ai créé un modèle d'article en BO WordPresse.

**Comment by nicolastrenti** [comment]
Livré en prod.
Aurélien a désormais la main pour créer de nouveaux billets (procédure transmise par mail)
