### ISSUE TITLE
URGENT - Burger Menu

### ISSUE THREAD

**Issue by LidwineMALTETE** [ampize/ampize-nr-tmv#99]
Bonjour, 

Ce matin nous rencontrons des problèmes pour l'ouverture du burger menu : au clic le menu ne s'ouvre pas et toute la page se décale vers la gauche. J'ai rechargé la page et le burger marchait de nouveau sur la home mais en allant dans la catégorie restos, de nouveau problème pour ouvrir le burger. 
Sur mobile également, le burger menu ne s'ouvre pas à chaque fois. 

Merci par avance de traiter en priorité ce point assez bloquant. 

A bientôt, 
Lidwine

**Comment by nicolastrenti** [comment]
Ce bug sera corrigé par la republication du site en prod

**Comment by nicolastrenti** [comment]
Problème résolu

**Comment by LidwineMALTETE** [comment]
Top ! Merci
